
USE [UserAuth]
GO
ALTER TABLE [dbo].[Users] DROP CONSTRAINT [DF__Users__CreatedAt__25869641]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 16-04-2026 8:16:14 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
DROP TABLE [dbo].[Users]
GO
USE [master]
GO
/****** Object:  Database [UserAuth]    Script Date: 16-04-2026 8:16:14 ******/
DROP DATABASE [UserAuth]
GO
/****** Object:  Database [UserAuth]    Script Date: 16-04-2026 8:16:14 ******/
CREATE DATABASE [UserAuth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserAuth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserAuth.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserAuth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UserAuth_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UserAuth] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserAuth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UserAuth] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UserAuth] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UserAuth] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UserAuth] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UserAuth] SET ARITHABORT OFF 
GO
ALTER DATABASE [UserAuth] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UserAuth] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UserAuth] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UserAuth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UserAuth] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UserAuth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UserAuth] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UserAuth] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UserAuth] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UserAuth] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UserAuth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UserAuth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UserAuth] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UserAuth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UserAuth] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UserAuth] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UserAuth] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UserAuth] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [UserAuth] SET  MULTI_USER 
GO
ALTER DATABASE [UserAuth] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UserAuth] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UserAuth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UserAuth] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UserAuth] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UserAuth] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [UserAuth] SET QUERY_STORE = OFF
GO
USE [UserAuth]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 16-04-2026 8:16:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[Mobile] [nvarchar](20) NOT NULL,
	[PasswordHash] [nvarchar](max) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getutcdate()) FOR [CreatedAt]
GO
USE [master]
GO
ALTER DATABASE [UserAuth] SET  READ_WRITE 
GO
